ALTER TABLE ar_clothes CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE boards CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE breed_tags CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE clothes CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE clothes_photos CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE colors CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE comments CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE personal_colors CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE petsize CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE petsnal_colors CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE prefers CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE sizeclothes CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE sizes CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE stores CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE users CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;



